name: CI/CD Deploy to EC2

on:
  push:
    branches:
      - main

# Required for GitHub OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::739013795335:role/OIDC_ROLE
          aws-region: us-east-1


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask App
        run: |
          cd backend
          nohup python app.py > flask.log 2>&1 &
          sleep 15

      - name: Health Check
        run: |
          curl --fail http://127.0.0.1:5000/api/ || curl --fail http://127.0.0.1:5000/api

     

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm send-command \
            --targets "Key=tag:Name,Values=MyServer" \
            --document-name "AWS-RunShellScript" \
            --comment "GitHub Actions Deployment" \
            --parameters 'commands=[
              "cd /home/ec2-user/aws-ecommerce-otp-authentication/backend",
              "git pull origin main",
              "pip3 install -r requirements.txt",
              "pkill -f app.py || true",
              "nohup python3 app.py > app.log 2>&1 &"
            ]'
